[BraincubeProvider] Provides Braincube OAuth 2.0 support for the PHP League's OAuth 2.0 Client
braincube-io/oauth2-php pull request #1
Opened 2017-05-04 08:10 UTC by likeavirgil

2017-07-12 08:18 UTC, damien-braincube commented on README.md
> +
On force l'utilisation de composer, il faudrait l'ajouter dans le README et mettre un lien vers l'install

2017-08-28 10:56 UTC, likeavirgil commented on README.md
> +
https://github.com/braincube-io/oauth2-php/pull/1/commits/cb069e1302fcc848525008eb7dc9ffb91175323e

2017-09-04 08:29 UTC, damien-braincube requested changes

2017-09-04 08:29 UTC, damien-braincube commented on LICENSE
> +The MIT License (MIT)
Pouquoi MIT au lieu de Apache ?

2017-09-04 08:29 UTC, damien-braincube commented on README.md
> +    'clientId'          => '{braincube-app-id}',
Commentaire sur APP id

2017-09-04 08:29 UTC, damien-braincube commented on README.md
> +    'clientSecret'      => '{braincube-app-secret}',
Commentaire sur APP secret, car c'est pas clair de savoir quoi mettre

2017-09-04 08:29 UTC, damien-braincube commented on src/Provider/Braincube.php
> +
Ajouter des commentaires

2017-09-04 08:29 UTC, damien-braincube commented on src/Provider/Braincube.php
> +            $message = $data['error']['type'].': '.$data['error']['message'];
error n'est pas forcement un tableau

```
if (!empty($data['error'])) {
            $error = $data['error'];

            if (is_array($error)) {
                $message = $error['type'].': '.$error['message'];
                throw new IdentityProviderException($message, $data['error']['code'], $data);
            } else {
                throw new IdentityProviderException($error, -1, $data);
            }

        }
```

2017-09-04 08:29 UTC, damien-braincube commented on src/Provider/Braincube.php
> +        return 'https://mybraincube.com/sso-server';
Ajouter en tant que paramétre de construction avec valeur par default (pour générer les serveurs de tests)

2017-09-04 08:29 UTC, damien-braincube commented on src/Provider/BraincubeUser.php
> +class BraincubeUser implements ResourceOwnerInterface
Ajout de commentaires

2017-09-04 09:52 UTC, likeavirgil commented on LICENSE
> +The MIT License (MIT)
La source du fork est en MIT donc j'ai laissé tel quel, tu t'y connais plus que moi en licence, je peux passer en Apache s'il le faut.

2017-09-04 09:54 UTC, likeavirgil commented on README.md
> +    'clientId'          => '{braincube-app-id}',
J'ai mis la doc du projet source https://github.com/braincube-io/oauth2-php/pull/1/commits/15ef11d2a648f637c13a51d484364d3aa9996bc0 la partie documentation spécifique à braincube sera écrite sur braincube.io (procédure pour obtenir ces deux paramètres).

2017-09-04 09:55 UTC, likeavirgil commented on README.md
> +    'clientSecret'      => '{braincube-app-secret}',
Cf https://github.com/braincube-io/oauth2-php/pull/1#discussion_r136785714

2017-09-04 09:57 UTC, likeavirgil commented on src/Provider/Braincube.php
> +            $message = $data['error']['type'].': '.$data['error']['message'];
https://github.com/braincube-io/oauth2-php/pull/1/commits/409e5da7add62f822225bf33b5534314f2ff7394

2017-09-20 09:51 UTC, likeavirgil commented on src/Provider/BraincubeUser.php
> +class BraincubeUser implements ResourceOwnerInterface
https://github.com/braincube-io/oauth2-php/pull/1/commits/ea86e17be2880191d7d5d7bc1c4ba8461bc2e6a0

2017-09-20 09:53 UTC, likeavirgil commented on src/Provider/Braincube.php
> +
https://github.com/braincube-io/oauth2-php/pull/1/commits/ae95220eb52091219c458e27dd2c76aafaf4c35a

2017-09-25 10:39 UTC, likeavirgil commented on src/Provider/Braincube.php
> +        return 'https://mybraincube.com/sso-server';
https://github.com/braincube-io/oauth2-php/pull/1/commits/1373282272c428c533f7e6727988009dff0f038f

2017-10-02 12:54 UTC, merged